In [ ]:
import requests
import pandas as pd
from sqlalchemy import create_engine , text 
import psycopg2
import json

In [20]:
import http.client

conn = http.client.HTTPSConnection("api.collectapi.com")

headers = {
    'content-type': "application/json",
    'authorization': "apikey 73DOJDq7FlKjuF822UAlSC:0WkfGnBB37XqDqeHiYeqdv"
    }

conn.request("GET", "/gasPrice/stateUsaPrice?state=WA", headers=headers)

res = conn.getresponse()
data = res.read()
decoded_data = data.decode("utf-8")

print(decoded_data)

{"success":true,"result":{"state":[{"currency":"usd","name":"Washington","lowername":"washington","gasoline":"5.6060","midGrade":"5.8620","premium":"6.1230","diesel":"6.5600"}],"cities":[{"currency":"usd","gasoline":"5.5120","midGrade":"5.8410","premium":"6.0990","diesel":"6.2240","name":"Bellingham","lowername":"bellingham"},{"currency":"usd","gasoline":"5.7650","midGrade":"6.0040","premium":"6.2220","diesel":"6.5830","name":"Bremerton","lowername":"bremerton"},{"currency":"usd","gasoline":"5.6020","midGrade":"5.7670","premium":"5.9550","diesel":"6.7320","name":"Olympia","lowername":"olympia"},{"currency":"usd","gasoline":"5.2460","midGrade":"5.5250","premium":"5.7590","diesel":"6.2080","name":"Richland-Kennewick-Pasco","lowername":"richland-kennewick-pasco"},{"currency":"usd","gasoline":"5.8570","midGrade":"6.0740","premium":"6.3340","diesel":"6.8140","name":"Seattle-Bellevue-Everett","lowername":"seattle-bellevue-everett"},{"currency":"usd","gasoline":"5.1660","midGrade":"5.4600","premium":"5.7100","diesel":"6.2450","name":"Spokane","lowername":"spokane"},{"currency":"usd","gasoline":"5.7290","midGrade":"5.9440","premium":"6.2060","diesel":"6.7330","name":"Tacoma","lowername":"tacoma"},{"currency":"usd","gasoline":"5.3870","midGrade":"5.7070","premium":"5.9170","diesel":"6.3650","name":"Yakima","lowername":"yakima"},{"currency":"usd","gasoline":"5.5480","midGrade":"5.7930","premium":"6.0510","diesel":"6.3890","name":"Vancouver","lowername":"vancouver"},{"currency":"usd","gasoline":"4.9790","midGrade":"0.0000","premium":"4.8590","diesel":"6.0840","name":"Clarkson","lowername":"clarkson"},{"currency":"usd","gasoline":"5.5860","midGrade":"5.7990","premium":"6.0570","diesel":"6.4840","name":"Longview","lowername":"longview"},{"currency":"usd","gasoline":"5.4470","midGrade":"5.6110","premium":"5.8100","diesel":"6.2950","name":"Mount Vernon-Anacortes","lowername":"mount vernon-anacortes"},{"currency":"usd","gasoline":"5.4530","midGrade":"5.7850","premium":"6.0790","diesel":"6.6050","name":"Walla Walla","lowername":"walla walla"},{"currency":"usd","gasoline":"5.2380","midGrade":"5.4630","premium":"5.6480","diesel":"6.2850","name":"Wenatchee","lowername":"wenatchee"}]}}

In [ ]:
data_json = data.json()
data

AttributeError: 'bytes' object has no attribute 'json'

In [22]:
data_json = json.loads(decoded_data)
data_json

{'success': True,
 'result': {'state': [{'currency': 'usd',
    'name': 'Washington',
    'lowername': 'washington',
    'gasoline': '5.6060',
    'midGrade': '5.8620',
    'premium': '6.1230',
    'diesel': '6.5600'}],
  'cities': [{'currency': 'usd',
    'gasoline': '5.5120',
    'midGrade': '5.8410',
    'premium': '6.0990',
    'diesel': '6.2240',
    'name': 'Bellingham',
    'lowername': 'bellingham'},
   {'currency': 'usd',
    'gasoline': '5.7650',
    'midGrade': '6.0040',
    'premium': '6.2220',
    'diesel': '6.5830',
    'name': 'Bremerton',
    'lowername': 'bremerton'},
   {'currency': 'usd',
    'gasoline': '5.6020',
    'midGrade': '5.7670',
    'premium': '5.9550',
    'diesel': '6.7320',
    'name': 'Olympia',
    'lowername': 'olympia'},
   {'currency': 'usd',
    'gasoline': '5.2460',
    'midGrade': '5.5250',
    'premium': '5.7590',
    'diesel': '6.2080',
    'name': 'Richland-Kennewick-Pasco',
    'lowername': 'richland-kennewick-pasco'},
   {'currency': 'usd',
    'gasoline': '5.8570',
    'midGrade': '6.0740',
    'premium': '6.3340',
    'diesel': '6.8140',
    'name': 'Seattle-Bellevue-Everett',
    'lowername': 'seattle-bellevue-everett'},
   {'currency': 'usd',
    'gasoline': '5.1660',
    'midGrade': '5.4600',
    'premium': '5.7100',
    'diesel': '6.2450',
    'name': 'Spokane',
    'lowername': 'spokane'},
   {'currency': 'usd',
    'gasoline': '5.7290',
    'midGrade': '5.9440',
    'premium': '6.2060',
    'diesel': '6.7330',
    'name': 'Tacoma',
    'lowername': 'tacoma'},
   {'currency': 'usd',
    'gasoline': '5.3870',
    'midGrade': '5.7070',
    'premium': '5.9170',
    'diesel': '6.3650',
    'name': 'Yakima',
    'lowername': 'yakima'},
   {'currency': 'usd',
    'gasoline': '5.5480',
    'midGrade': '5.7930',
    'premium': '6.0510',
    'diesel': '6.3890',
    'name': 'Vancouver',
    'lowername': 'vancouver'},
   {'currency': 'usd',
    'gasoline': '4.9790',
    'midGrade': '0.0000',
    'premium': '4.8590',
    'diesel': '6.0840',
    'name': 'Clarkson',
    'lowername': 'clarkson'},
   {'currency': 'usd',
    'gasoline': '5.5860',
    'midGrade': '5.7990',
    'premium': '6.0570',
    'diesel': '6.4840',
    'name': 'Longview',
    'lowername': 'longview'},
   {'currency': 'usd',
    'gasoline': '5.4470',
    'midGrade': '5.6110',
    'premium': '5.8100',
    'diesel': '6.2950',
    'name': 'Mount Vernon-Anacortes',
    'lowername': 'mount vernon-anacortes'},
   {'currency': 'usd',
    'gasoline': '5.4530',
    'midGrade': '5.7850',
    'premium': '6.0790',
    'diesel': '6.6050',
    'name': 'Walla Walla',
    'lowername': 'walla walla'},
   {'currency': 'usd',
    'gasoline': '5.2380',
    'midGrade': '5.4630',
    'premium': '5.6480',
    'diesel': '6.2850',
    'name': 'Wenatchee',
    'lowername': 'wenatchee'}]}}

In [ ]:
city_prices_list = data_json['result']['cities']
city_prices_list

[{'currency': 'usd',
  'gasoline': '5.5120',
  'midGrade': '5.8410',
  'premium': '6.0990',
  'diesel': '6.2240',
  'name': 'Bellingham',
  'lowername': 'bellingham'},
 {'currency': 'usd',
  'gasoline': '5.7650',
  'midGrade': '6.0040',
  'premium': '6.2220',
  'diesel': '6.5830',
  'name': 'Bremerton',
  'lowername': 'bremerton'},
 {'currency': 'usd',
  'gasoline': '5.6020',
  'midGrade': '5.7670',
  'premium': '5.9550',
  'diesel': '6.7320',
  'name': 'Olympia',
  'lowername': 'olympia'},
 {'currency': 'usd',
  'gasoline': '5.2460',
  'midGrade': '5.5250',
  'premium': '5.7590',
  'diesel': '6.2080',
  'name': 'Richland-Kennewick-Pasco',
  'lowername': 'richland-kennewick-pasco'},
 {'currency': 'usd',
  'gasoline': '5.8570',
  'midGrade': '6.0740',
  'premium': '6.3340',
  'diesel': '6.8140',
  'name': 'Seattle-Bellevue-Everett',
  'lowername': 'seattle-bellevue-everett'},
 {'currency': 'usd',
  'gasoline': '5.1660',
  'midGrade': '5.4600',
  'premium': '5.7100',
  'diesel': '6.2450',
  'name': 'Spokane',
  'lowername': 'spokane'},
 {'currency': 'usd',
  'gasoline': '5.7290',
  'midGrade': '5.9440',
  'premium': '6.2060',
  'diesel': '6.7330',
  'name': 'Tacoma',
  'lowername': 'tacoma'},
 {'currency': 'usd',
  'gasoline': '5.3870',
  'midGrade': '5.7070',
  'premium': '5.9170',
  'diesel': '6.3650',
  'name': 'Yakima',
  'lowername': 'yakima'},
 {'currency': 'usd',
  'gasoline': '5.5480',
  'midGrade': '5.7930',
  'premium': '6.0510',
  'diesel': '6.3890',
  'name': 'Vancouver',
  'lowername': 'vancouver'},
 {'currency': 'usd',
  'gasoline': '4.9790',
  'midGrade': '0.0000',
  'premium': '4.8590',
  'diesel': '6.0840',
  'name': 'Clarkson',
  'lowername': 'clarkson'},
 {'currency': 'usd',
  'gasoline': '5.5860',
  'midGrade': '5.7990',
  'premium': '6.0570',
  'diesel': '6.4840',
  'name': 'Longview',
  'lowername': 'longview'},
 {'currency': 'usd',
  'gasoline': '5.4470',
  'midGrade': '5.6110',
  'premium': '5.8100',
  'diesel': '6.2950',
  'name': 'Mount Vernon-Anacortes',
  'lowername': 'mount vernon-anacortes'},
 {'currency': 'usd',
  'gasoline': '5.4530',
  'midGrade': '5.7850',
  'premium': '6.0790',
  'diesel': '6.6050',
  'name': 'Walla Walla',
  'lowername': 'walla walla'},
 {'currency': 'usd',
  'gasoline': '5.2380',
  'midGrade': '5.4630',
  'premium': '5.6480',
  'diesel': '6.2850',
  'name': 'Wenatchee',
  'lowername': 'wenatchee'}]

In [28]:
cities=data_json['result']['cities']
type(cities)

list

In [29]:
city_prices_df = pd.DataFrame(cities)
city_prices_df.head()

,currency,gasoline,midGrade,premium,diesel,name,lowername
0,usd,5.5120,5.8410,6.0990,6.2240,Bellingham,bellingham
1,usd,5.7650,6.0040,6.2220,6.5830,Bremerton,bremerton
2,usd,5.6020,5.7670,5.9550,6.7320,Olympia,olympia
3,usd,5.2460,5.5250,5.7590,6.2080,Richland-Kennewick-Pasco,richland-kennewick-pasco
4,usd,5.8570,6.0740,6.3340,6.8140,Seattle-Bellevue-Everett,seattle-bellevue-everett

In [30]:
city_prices_df.rename(columns={'name':'city_name','midGrade':'mid_grade'},inplace=True)
city_prices_df.head()

,currency,gasoline,mid_grade,premium,diesel,city_name,lowername
0,usd,5.5120,5.8410,6.0990,6.2240,Bellingham,bellingham
1,usd,5.7650,6.0040,6.2220,6.5830,Bremerton,bremerton
2,usd,5.6020,5.7670,5.9550,6.7320,Olympia,olympia
3,usd,5.2460,5.5250,5.7590,6.2080,Richland-Kennewick-Pasco,richland-kennewick-pasco
4,usd,5.8570,6.0740,6.3340,6.8140,Seattle-Bellevue-Everett,seattle-bellevue-everett

In [31]:
city_prices_df.drop(columns=['lowername'],inplace=True)
city_prices_df.head()

  currency gasoline mid_grade premium  diesel                 city_name
0      usd   5.5120    5.8410  6.0990  6.2240                Bellingham
1      usd   5.7650    6.0040  6.2220  6.5830                 Bremerton
2      usd   5.6020    5.7670  5.9550  6.7320                   Olympia
3      usd   5.2460    5.5250  5.7590  6.2080  Richland-Kennewick-Pasco
4      usd   5.8570    6.0740  6.3340  6.8140  Seattle-Bellevue-Everett

In [32]:
DATABASE_NAME = 'postgres'
DATABASE_USER = 'postgres'
DATABASE_PORT = 5432
DATABASE_PASSWORD = '123456'
DATABASE_HOST = 'localhost'

engine = create_engine(f'postgresql+psycopg2://{DATABASE_USER}:{DATABASE_PASSWORD}@{DATABASE_HOST}:{DATABASE_PORT}/{DATABASE_NAME}')

In [33]:
city_prices_df.to_sql('city_prices',engine , if_exists='replace',index=False )

14

In [34]:
with engine.connect() as conn:
    resort = conn.execute(text('select * from city_prices;'))
    for i in resort:
        print(i)

('usd', '5.5120', '5.8410', '6.0990', '6.2240', 'Bellingham')
('usd', '5.7650', '6.0040', '6.2220', '6.5830', 'Bremerton')
('usd', '5.6020', '5.7670', '5.9550', '6.7320', 'Olympia')
('usd', '5.2460', '5.5250', '5.7590', '6.2080', 'Richland-Kennewick-Pasco')
('usd', '5.8570', '6.0740', '6.3340', '6.8140', 'Seattle-Bellevue-Everett')
('usd', '5.1660', '5.4600', '5.7100', '6.2450', 'Spokane')
('usd', '5.7290', '5.9440', '6.2060', '6.7330', 'Tacoma')
('usd', '5.3870', '5.7070', '5.9170', '6.3650', 'Yakima')
('usd', '5.5480', '5.7930', '6.0510', '6.3890', 'Vancouver')
('usd', '4.9790', '0.0000', '4.8590', '6.0840', 'Clarkson')
('usd', '5.5860', '5.7990', '6.0570', '6.4840', 'Longview')
('usd', '5.4470', '5.6110', '5.8100', '6.2950', 'Mount Vernon-Anacortes')
('usd', '5.4530', '5.7850', '6.0790', '6.6050', 'Walla Walla')
('usd', '5.2380', '5.4630', '5.6480', '6.2850', 'Wenatchee')